<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="music"
    nsURI="http://www.eclipse.org/emf/texo/test/model/samples/music" nsPrefix="org.elver.music">
  <eClassifiers xsi:type="ecore:EClass" name="Artist" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genre" eType="#//Genre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artist" eType="#//Artist"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="releaseDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genres" upperBound="-1"
        eType="#//Genre">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@ManyToMany"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="songs" upperBound="-1"
        eType="#//Song">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@OneToMany"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ratings" unique="false"
        upperBound="-1" eType="#//Rating"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Genre" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Rating">
    <eLiterals name="LOW"/>
    <eLiterals name="HIGH" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Song" eSuperTypes="identifiable.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="track" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
